---
name: Build and Push to Cachix

on:
  push:
  workflow_dispatch:
  # Ensure derivation does not make mynix cache stale  
  schedule:
    - cron: "0 2 * * *"  # UTC
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - my-go
          - kubernetes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: mynix-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Nix package
        # non-flake version
        # run: nix-build --attr "${{ matrix.package }}"
        run: nix build .#${{ matrix.package }}
