---
name: Nix update

on:  # yamllint disable-line rule:truthy
  # push:
  workflow_dispatch:

jobs:
  nix-update:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      # Also Settings > Actions > General
      # [x] Allow GitHub Actions to create and approve pull requests
      pull-requests: write
    strategy:
      matrix:
        package:
          - kubernetes
          - sf
          - statusbar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update package
        run: nix run github:Mic92/nix-update -- --flake ${{ matrix.package }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
