---
name: Nix update

on:  # yamllint disable-line rule:truthy
  # push:
  workflow_dispatch:

jobs:
  nix-update:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install nix-update
        uses: yaxitech/nix-install-pkgs-action@v3
        with:
          packages: "nix-update"
          inputs-from: nixpkgs

      - name: Run nix-update
        run: nix-update --flake kubernetes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
